// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_A6OIniBto1HGzQUskBKcz53V8aj2r8',
    appId: '1:105416666304:web:be084d62ab619bf60cd125',
    messagingSenderId: '105416666304',
    projectId: 'fir-project-f704d',
    authDomain: 'fir-project-f704d.firebaseapp.com',
    storageBucket: 'fir-project-f704d.firebasestorage.app',
    measurementId: 'G-WLNEQ7SRPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmpgIJbWHFeRbPQ_iL6CjL9ymm4sewYM',
    appId: '1:105416666304:android:c493c12cc929d15d0cd125',
    messagingSenderId: '105416666304',
    projectId: 'fir-project-f704d',
    storageBucket: 'fir-project-f704d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqcZMPjTf3QhgvePV0nS0z24WyttGaNRM',
    appId: '1:105416666304:ios:fc8741875ff1e7b50cd125',
    messagingSenderId: '105416666304',
    projectId: 'fir-project-f704d',
    storageBucket: 'fir-project-f704d.firebasestorage.app',
    iosBundleId: 'com.example.flutterChaitra',
  );
}
